const slugify = require('slugify');

/* Rewriting the default create service generated by moleculer */
const handler = async function (ctx) {
  try {
    const { title, content, author } = ctx.params
    return await this._create(ctx, {
      title,
      slug: slugify(title, { lower: true, strict: true }),
      content,
      author
    })
  } catch (e) {
    return {
      success: false,
      error: e.message,
    }
  }
}
module.exports = {
  handler,
  params: {
    title: { type: 'string' },
    content: { type: 'string' },
    author: { type: 'string' }
  }
}